/* Program data registry — imported by Programs.jsx */
export const PROGRAM_REGISTRY = {
  'B.Tech Computer Science': {
    fees: '₹1.8L / year',
    avgSalary: '₹18 LPA',
    topRecruiters: ['Google', 'Microsoft', 'Amazon', 'Flipkart'],
    duration: '4 Years',
    seats: 120,
    level: 'UG',
    outcomes: '95% placed',
    accreditation: 'NAAC A++',
    highlight: 'AI, ML & Systems Design specialisation',
    badge: '🔥 Most Popular',
  },
  'MBA Business Analytics': {
    fees: '₹2.2L / year',
    avgSalary: '₹22 LPA',
    topRecruiters: ['McKinsey', 'Deloitte', 'Goldman Sachs', 'Meta'],
    duration: '2 Years',
    seats: 60,
    level: 'PG',
    outcomes: '100% placed',
    accreditation: 'AACSB',
    highlight: 'Live capstone with Fortune 500',
    badge: '⭐ Top Ranked',
  },
  'B.Sc Biotechnology': {
    fees: '₹1.1L / year',
    avgSalary: '₹9 LPA',
    topRecruiters: ["Dr. Reddy's", 'Biocon', 'Sun Pharma'],
    duration: '3 Years',
    seats: 80,
    level: 'UG',
    outcomes: '88% placed',
    accreditation: 'NAAC A++',
    highlight: 'CSIR-funded research labs',
    badge: '🧬 Research Focus',
  },
  'BA English Literature': {
    fees: '₹65K / year',
    avgSalary: '₹6 LPA',
    topRecruiters: ['HarperCollins', 'NDTV', 'Times Group'],
    duration: '3 Years',
    seats: 50,
    level: 'UG',
    outcomes: '82% placed',
    accreditation: 'NAAC A++',
    highlight: 'Creative writing + media track',
    badge: null,
  },
  'LLB Corporate Law': {
    fees: '₹1.5L / year',
    avgSalary: '₹14 LPA',
    topRecruiters: ['Khaitan & Co', 'AZB Partners', 'Shardul Amarchand'],
    duration: '5 Years',
    seats: 60,
    level: 'Integrated',
    outcomes: '91% placed',
    accreditation: 'BCI Approved',
    highlight: 'Moot court + corporate clinic',
    badge: '⚖️ Bar Council Approved',
  },
  'Ph.D Research Programs': {
    fees: '₹80K / year',
    avgSalary: '₹16 LPA',
    topRecruiters: ['ISRO', 'IITs', 'Stanford', 'MIT'],
    duration: '3–5 Years',
    seats: 30,
    level: 'Doctoral',
    outcomes: '100% fellowship',
    accreditation: 'UGC',
    highlight: '₹120Cr annual research grants',
    badge: '🔬 Fully Funded',
  },
};
