/* Program data registry — imported by Programs.jsx */
export const PROGRAM_REGISTRY = {
  'B.Tech Computer Science': {
    fees: '₹1.8L / year',
    avgSalary: '₹18 LPA',
    topRecruiters: ['Google', 'Microsoft', 'Amazon', 'Flipkart'],
    duration: '4 Years',
    seats: 120,
    level: 'UG',
    outcomes: '95% placed',
    accreditation: 'NAAC A++',
    highlight: 'AI, ML & Systems Design specialisation',
    badge: '🔥 Most Popular',
  },
  'MBA Business Analytics': {
    fees: '₹2.2L / year',
    avgSalary: '₹22 LPA',
    topRecruiters: ['McKinsey', 'Deloitte', 'Goldman Sachs', 'Meta'],
    duration: '2 Years',
    seats: 60,
    level: 'PG',
    outcomes: '100% placed',
    accreditation: 'AACSB',
    highlight: 'Live capstone with Fortune 500',
    badge: '⭐ Top Ranked',
  },
  'B.Sc Biotechnology': {
    fees: '₹1.1L / year',
    avgSalary: '₹9 LPA',
    topRecruiters: ["Dr. Reddy's", 'Biocon', 'Sun Pharma'],
    duration: '3 Years',
    seats: 80,
    level: 'UG',
    outcomes: '88% placed',
    accreditation: 'NAAC A++',
    highlight: 'CSIR-funded research labs',
    badge: '🧬 Research Focus',
  },
  'BA English Literature': {
    fees: '₹65K / year',
    avgSalary: '₹6 LPA',
    topRecruiters: ['HarperCollins', 'NDTV', 'Times Group'],
    duration: '3 Years',
    seats: 50,
    level: 'UG',
    outcomes: '82% placed',
    accreditation: 'NAAC A++',
    highlight: 'Creative writing + media track',
    badge: null,
  },
  'LLB Corporate Law': {
    fees: '₹1.5L / year',
    avgSalary: '₹14 LPA',
    topRecruiters: ['Khaitan & Co', 'AZB Partners', 'Shardul Amarchand'],
    duration: '5 Years',
    seats: 60,
    level: 'Integrated',
    outcomes: '91% placed',
    accreditation: 'BCI Approved',
    highlight: 'Moot court + corporate clinic',
    badge: '⚖️ Bar Council Approved',
  },
  'Ph.D Research Programs': {
    fees: '₹80K / year',
    avgSalary: '₹16 LPA',
    topRecruiters: ['ISRO', 'IITs', 'Stanford', 'MIT'],
    duration: '3–5 Years',
    seats: 30,
    level: 'Doctoral',
    outcomes: '100% fellowship',
    accreditation: 'UGC',
    highlight: '₹120Cr annual research grants',
    badge: '🔬 Fully Funded',
  },
  'B.Tech Electrical Engineering': {
    fees: '₹1.9L / year',
    avgSalary: '₹12 LPA',
    topRecruiters: ['Siemens', 'ABB', 'Schneider Electric', 'Tata Power'],
    duration: '4 Years',
    seats: 90,
    level: 'UG',
    outcomes: '88% placed',
    accreditation: 'NAAC A++',
    highlight: 'Smart grids & control systems',
    badge: '⚡ Power & Control Focus',
  },
  'B.Tech Civil Engineering': {
    fees: '₹1.7L / year',
    avgSalary: '₹11 LPA',
    topRecruiters: ['Larsen & Toubro', 'AECOM', 'Tata Projects', 'HCC'],
    duration: '4 Years',
    seats: 80,
    level: 'UG',
    outcomes: '86% placed',
    accreditation: 'NAAC A++',
    highlight: 'Resilient infrastructure studio projects',
    badge: '🏗️ Infrastructure Ready',
  },
  'MBA Finance': {
    fees: '₹2.5L / year',
    avgSalary: '₹21 LPA',
    topRecruiters: ['Goldman Sachs', 'Morgan Stanley', 'Deloitte', 'JP Morgan'],
    duration: '2 Years',
    seats: 60,
    level: 'PG',
    outcomes: '93% placed',
    accreditation: 'AACSB',
    highlight: 'Valuation, risk, and investment strategy',
    badge: '📈 Finance Leadership',
  },
  'M.Sc Data Science': {
    fees: '₹2.0L / year',
    avgSalary: '₹20 LPA',
    topRecruiters: ['Google', 'Amazon', 'Microsoft', 'Netflix'],
    duration: '2 Years',
    seats: 70,
    level: 'PG',
    outcomes: '89% placed',
    accreditation: 'NAAC A++',
    highlight: 'MLOps-ready analytics pipelines',
    badge: '🧠 Applied AI Track',
  },
};

/** Back-of-card flip content: placement ring %, pitch lines, hiring logos (Clearbit domain optional) */
export const PROGRAM_BACK_DETAILS = {
  'B.Tech Computer Science': {
    placementPct: 95,
    pitch: [
      'Industry-aligned CS with depth in algorithms, AI, and systems at scale.',
      'Strong internship pipelines into global product and cloud teams.',
    ],
    companies: [
      { name: 'Google', domain: 'google.com', blurb: 'Search, AI, and cloud products' },
      { name: 'Microsoft', domain: 'microsoft.com', blurb: 'Enterprise software and Azure cloud' },
      { name: 'Amazon', domain: 'amazon.com', blurb: 'E-commerce and AWS infrastructure' },
    ],
  },
  'MBA Business Analytics': {
    placementPct: 98,
    pitch: [
      'Data-driven leadership with live cases from Fortune 500 partners.',
      'Capstones in strategy, forecasting, and analytics consulting delivery.',
    ],
    companies: [
      { name: 'Goldman Sachs', domain: 'goldmansachs.com', blurb: 'Investment banking and securities' },
      { name: 'Deloitte', domain: 'deloitte.com', blurb: 'Management consulting and advisory' },
      { name: 'McKinsey', domain: 'mckinsey.com', blurb: 'Global strategy consulting' },
    ],
  },
  'B.Sc Biotechnology': {
    placementPct: 88,
    pitch: [
      'Hands-on life sciences with CSIR-linked labs and GMP exposure.',
      'Paths into pharma R&D, bioinformatics, and public-sector science.',
    ],
    companies: [
      { name: 'Biocon', domain: 'biocon.com', blurb: 'Biopharmaceutical research and manufacturing' },
      { name: 'ISRO', domain: null, blurb: 'Space biology and life sciences research' },
      { name: 'Infosys', domain: 'infosys.com', blurb: 'Healthcare IT and bioinformatics' },
    ],
  },
  'BA English Literature': {
    placementPct: 82,
    pitch: [
      'Critical reading, creative writing, and media literacy in one rigorous track.',
      'Alumni work in publishing, journalism, communications, and research.',
    ],
    companies: [
      { name: 'Times Group', domain: 'timesgroup.com', blurb: 'Journalism, media, and publishing' },
      { name: 'Deloitte', domain: 'deloitte.com', blurb: 'Communications and content strategy' },
      { name: 'McKinsey', domain: 'mckinsey.com', blurb: 'Research writing and knowledge' },
    ],
  },
  'LLB Corporate Law': {
    placementPct: 91,
    pitch: [
      'Integrated corporate law with moot courts and in-house legal clinics.',
      'Prepare for firm roles in banking, compliance, and advisory.',
    ],
    companies: [
      { name: 'Goldman Sachs', domain: 'goldmansachs.com', blurb: 'Legal compliance and regulatory affairs' },
      { name: 'HDFC', domain: 'hdfcbank.com', blurb: 'Banking law and financial regulation' },
      { name: 'Deloitte', domain: 'deloitte.com', blurb: 'Legal advisory and risk consulting' },
    ],
  },
  'Ph.D Research Programs': {
    placementPct: 100,
    pitch: [
      'Fully funded research across sciences with dedicated faculty mentors.',
      'Publish, patent, and place into national labs and global research groups.',
    ],
    companies: [
      { name: 'ISRO', domain: null, blurb: 'Funded doctoral research programs' },
      { name: 'Biocon', domain: 'biocon.com', blurb: 'Pharmaceutical R&D fellowships' },
      { name: 'Microsoft', domain: 'microsoft.com', blurb: 'Research internships and grants' },
    ],
  },
  'B.Tech Electrical Engineering': {
    placementPct: 86,
    pitch: [
      'Smart grids, embedded control, and renewable integration engineering.',
      'Project-based labs to build reliable systems that scale into industry.',
    ],
    companies: [
      { name: 'Siemens', domain: 'siemens.com', blurb: 'Industrial automation and power systems' },
      { name: 'ABB', domain: 'abb.com', blurb: 'Electrification and control solutions' },
      { name: 'Schneider Electric', domain: 'schneider-electric.com', blurb: 'Energy management and infrastructure' },
    ],
  },
  'B.Tech Civil Engineering': {
    placementPct: 84,
    pitch: [
      'Resilient infrastructure design with modern construction methodologies.',
      'Studio-led learning focused on planning, safety, and sustainable materials.',
    ],
    companies: [
      { name: 'Larsen & Toubro', domain: 'larsentoubro.com', blurb: 'Engineering, procurement, and construction' },
      { name: 'AECOM', domain: 'aecom.com', blurb: 'Architecture and infrastructure advisory' },
      { name: 'Tata Projects', domain: 'tataprojects.com', blurb: 'Project delivery for energy and buildings' },
    ],
  },
  'MBA Finance': {
    placementPct: 93,
    pitch: [
      'Investment strategy, risk modeling, and decision-ready valuation frameworks.',
      'Capstones that simulate real markets with responsible financial leadership.',
    ],
    companies: [
      { name: 'Goldman Sachs', domain: 'goldmansachs.com', blurb: 'Investment banking and securities' },
      { name: 'Morgan Stanley', domain: 'morganstanley.com', blurb: 'Global investment management and advisory' },
      { name: 'Deloitte', domain: 'deloitte.com', blurb: 'Advisory for finance and risk transformations' },
    ],
  },
  'M.Sc Data Science': {
    placementPct: 89,
    pitch: [
      'Scalable pipelines for insights, ML, and production deployment at scale.',
      'MLOps-first approach with evaluation, monitoring, and responsible AI practices.',
    ],
    companies: [
      { name: 'Google', domain: 'google.com', blurb: 'AI research, ML platforms, and cloud services' },
      { name: 'Amazon', domain: 'amazon.com', blurb: 'E-commerce and AWS infrastructure' },
      { name: 'Microsoft', domain: 'microsoft.com', blurb: 'Cloud analytics and ML deployment tools' },
    ],
  },
};
